apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: site24x7-apminsight-dataexporter-daemonset
spec:
  selector:
    matchLabels:
      app: site24x7-apminsight-dataexporter
  template:
    metadata:
      labels:
        app: site24x7-apminsight-dataexporter
    spec:
      containers:
      - name: site24x7-apminsight-dataexporter-container
        image: site24x7/apminsight-dataexporter:latest
        ports:
        - containerPort: 20021
        - containerPort: 20022
        resources: 
          requests: 
              cpu: 100m 
              memory: 200Mi 
          limits: 
              cpu: 500m 
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: site24x7-apminsight-dataexporter-service
spec:
  selector:
    app: site24x7-apminsight-dataexporter
  ports:
    - name: statusport
      protocol: TCP
      port: 20021
      targetPort: 20021
    - name: dataport
      protocol: TCP
      port: 20022
      targetPort: 20022
