apiVersion: v1
kind: ServiceAccount
metadata:
  name: site24x7
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: site24x7
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  - componentstatuses
  - events
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  resourceNames:
  - site24x7
  verbs: ["list", "watch", "get", "patch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["events.k8s.io"]
  resources:
  - events
  verbs: ["list","watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources:
  - certificatesigningrequests
  verbs: ["list", "watch"]
- apiGroups:  # Kubelet connectivity
  - ""
  resources:
  - nodes/metrics
  - nodes/stats
  - nodes/metrics/cadvisor
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /healthz
  - /livez
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: site24x7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: site24x7
subjects:
- kind: ServiceAccount
  name: site24x7
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site24x7
  namespace: default
  labels:
    app.kubernetes.io/name: site24x7
    app.kubernetes.io/component: agent
    app.kubernetes.io/owner: site24x7
data:
  NODE_AGENT_VERSION: "2000"
  CLUSTER_AGENT_VERSION: "100"
  SETTINGS: |
    {
      "kubernetes": "300",
      "daemonsets": "300",
      "deployments": "300",
      "statefulsets": "300",
      "pods": "300",
      "nodes": "300",
      "services": "300",
      "replicasets": "900",
      "ingresses": "300",
      "jobs": "300",
      "pv": "300",
      "persistentvolumeclaim": "300",
      "componentstatuses": "300",
      "horizontalpodautoscalers": "300",
      "endpoints": "3600",
      "namespaces": "300",
      "eventcollector": "60",
      "npcdatacollector": "300",
      "npcdatacollector_discovery": "900",
      "resourcedependency": "300",
      "workloadsdatacollector": "300",
      "workloadsdatacollector_discovery": "900",
      "clustermetricsaggregator": "300",
      "sidecarnpccollector": "300",
      "sidecarnpccollector_discovery": "900",
      "dcinit": "900",
      "clusteragent": "1",
      "ksm": "1",
      "guidancemetrics": "20600",
      "termination": "900",
      "kubelet": "300",
      "metadata": "20600",
      "prometheus_integration": "1",
      "plugin_integration": "1",
      "database_integration": "1",
      "ksmprocessor": "1",
      "kubeletdatapersistence": "1",
      "servicerelationdataprocessor": "1",
      "yamlfetcher": "60"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: site24x7-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: site24x7-agent
  updateStrategy:
      type: RollingUpdate # Only supported in Kubernetes version 1.6 or later.
  template:
    metadata:
      labels:      
        app: site24x7-agent
      name: site24x7-agent
    spec:
      serviceAccountName: site24x7          
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: site24x7/docker-agent:release2000
        imagePullPolicy: Always
        name: site24x7-agent
        # securityContext:
        #   capabilities:
        #     drop:
        #       - ALL
        #   seccompProfile:
        #     type: RuntimeDefault
        #   allowPrivilegeEscalation: false
        #   readOnlyRootFilesystem: true
        #   runAsNonRoot: true
        #   runAsUser: 1001010001
        env:
          - name: KEY
            valueFrom:
              secretKeyRef:
                name: "site24x7-agent"
                key: KEY
          - name: installer
            value: kubernetes
          - name: NODE_IP
            valueFrom:
              fieldRef:
                 fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: procfs
            mountPath: /host/proc
            readOnly: true
          - name: sysfs
            mountPath: /host/sys/
            readOnly: true
          - name: varfs
            mountPath: /host/var/
            readOnly: true
          - name: etcfs
            mountPath: /host/etc/
            readOnly: true
          - name: site24x7-agent
            mountPath: /opt/site24x7/
          - name: clusterconfig
            mountPath: /etc/site24x7/clusterconfig
            readOnly: true
      volumes:
        - hostPath:
            path: /proc
          name: procfs
        - hostPath:
            path: /sys/
          name: sysfs
        - hostPath:
            path: /var/
          name: varfs
        - hostPath:
            path: /etc/
          name: etcfs
        - emptyDir: {}
          name: site24x7-agent
        - configMap:
            name: site24x7
            optional: true
          name: clusterconfig
