apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: site24x7-apminsight-dataexporter-daemonset
spec:
  selector:
    matchLabels:
      app: site24x7-apminsight-dataexporter
  template:
    metadata:
      labels:
        app: site24x7-apminsight-dataexporter
    spec:
      containers:
      - name: site24x7-apminsight-dataexporter-container
        image: site24x7/apminsight-dataexporter:latest
        env:
        - name: S247_LICENSE_KEY
          value: "<license_key>"
        ports:
        - containerPort: 20021
        - containerPort: 20022
        - containerPort: 20023
---
apiVersion: v1
kind: Service
metadata:
  name: site24x7-apminsight-dataexporter-service
spec:
  selector:
    app: apminsight-dataexporter
  ports:
    - name: statusport
      protocol: TCP
      port: 20021
      targetPort: 20021
    - name: dataport
      protocol: TCP
      port: 20022
      targetPort: 20022
    - name: downloadport
      protocol: TCP
      port: 20023
